### ISSUE TITLE
error in debug mode

### ISSUE THREAD

**Issue by drdhaval2785** [kmadathil/sanskrit_parser#11]
error in debug mode
```
$ python lexical_analyzer/SanskritLexicalAnalyzer.py astyuttarasyAmdishi --spli
t --debug
Parsing of XMLs started at 2017-07-06 21:23:52.769000
666994 forms cached for quick search
Parsing of XMLs completed at 2017-07-06 21:23:58.202000
Input String: astyuttarasyAmdishi
Input String in SLP1: astyuttarasyAmdiSi
Start split: 2017-07-06 21:24:01.603000
Splitting  astyuttarasyAmdiSi
Left, Right substrings = a styuttarasyAmdiSi
s_c_list: [[u'a', u'styuttarasyAmdiSi']]
Invalid left word:  a
Left, Right substrings = as tyuttarasyAmdiSi
Context Sandhi match: (None, 's', '[tTkKpP]') as tyuttarasyAmdiSi
Trying: s_
Trying: r_
s_c_list: [[u'as', u'tyuttarasyAmdiSi'], [u'ar', u'tyuttarasyAmdiSi']]
Invalid left word:  as
Invalid left word:  ar
Left, Right substrings = ast yuttarasyAmdiSi
s_c_list: [[u'ast', u'yuttarasyAmdiSi']]
Invalid left word:  ast
Left, Right substrings = asty uttarasyAmdiSi
Context Sandhi match: (None, 'y', '[aAuUeEoO]') asty uttarasyAmdiSi
Trying: i_
Trying: I_
s_c_list: [[u'asty', u'uttarasyAmdiSi'], [u'asti', u'uttarasyAmdiSi'], [u'astI', u'uttarasyAmdiSi']]
Invalid left word:  asty
Valid left split:  asti
Traceback (most recent call last):
  File "lexical_analyzer/SanskritLexicalAnalyzer.py", line 406, in <module>
    main()
  File "lexical_analyzer/SanskritLexicalAnalyzer.py", line 402, in main
    splits=s.getSandhiSplits(i,sort=not args.no_sort,debug=args.debug)
  File "lexical_analyzer/SanskritLexicalAnalyzer.py", line 246, in getSandhiSplits
    ps = self._possible_splits(s,debug)
  File "lexical_analyzer/SanskritLexicalAnalyzer.py", line 338, in _possible_splits
    print "Valid left split: ", s_c_left, self.tag_cache[s_c_left]
KeyError: u'asti'
```

The normal mode functions as expected.

**Comment by kmadathil** [comment]
Fixed
