### ISSUE TITLE
IsADirectoryError

### ISSUE THREAD

**Issue by vvasuki** [kmadathil/sanskrit_parser#171]
https://github.com/kmadathil/sanskrit_parser/blob/master/sanskrit_parser/output_utils/__init__.py इत्यस्य चालनेन 

```
/usr/bin/python3.9 /home/vvasuki/sanskrit-coders/sanskrit_parser/sanskrit_parser/output/__init__.py
Traceback (most recent call last):
  File "/home/vvasuki/sanskrit-coders/sanskrit_parser/sanskrit_parser/output/__init__.py", line 1, in <module>
    from sanskrit_parser import Parser
  File "/home/vvasuki/sanskrit-coders/sanskrit_parser/sanskrit_parser/__init__.py", line 19, in <module>
    from .api import Parser
  File "/home/vvasuki/sanskrit-coders/sanskrit_parser/sanskrit_parser/api.py", line 53, in <module>
    from sanskrit_parser.parser.sandhi_analyzer import LexicalSandhiAnalyzer
  File "/home/vvasuki/sanskrit-coders/sanskrit_parser/sanskrit_parser/parser/sandhi_analyzer.py", line 70, in <module>
    from .datastructures import SandhiGraph
  File "/home/vvasuki/sanskrit-coders/sanskrit_parser/sanskrit_parser/parser/datastructures.py", line 26, in <module>
    dw = DhatuWrapper()
  File "/home/vvasuki/sanskrit-coders/sanskrit_parser/sanskrit_parser/util/DhatuWrapper.py", line 26, in __init__
    with importlib.resources.path('sanskrit_parser', 'data') as data_dir:
  File "/usr/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/usr/lib/python3.9/importlib/resources.py", line 175, in _path_from_reader
    opener_reader = reader.open_resource(norm_resource)
  File "<frozen importlib._bootstrap_external>", line 1060, in open_resource
IsADirectoryError: [Errno 21] Is a directory: '/home/vvasuki/sanskrit-coders/sanskrit_parser/sanskrit_parser/data'
```
इति लभे। किमत्र विधेयम्?

**Comment by kmadathil** [comment]
```
lint run-test: commands[0] | flake8 sanskrit_parser tests --exclude tests/KISS

sanskrit_parser/output_utils/__init__.py:3:1: E302 expected 2 blank lines, found 1

sanskrit_parser/output_utils/__init__.py:4:3: E111 indentation is not a multiple of 4

sanskrit_parser/output_utils/__init__.py:5:3: E111 indentation is not a multiple of 4

sanskrit_parser/output_utils/__init__.py:7:3: E111 indentation is not a multiple of 4

sanskrit_parser/output_utils/__init__.py:8:3: E111 indentation is not a multiple of 4

sanskrit_parser/output_utils/__init__.py:11:7: E111 indentation is not a multiple of 4

sanskrit_parser/output_utils/__init__.py:12:7: E111 indentation is not a multiple of 4

sanskrit_parser/output_utils/__init__.py:15:11: E111 indentation is not a multiple of 4

sanskrit_parser/output_utils/__init__.py:17:11: E114 indentation is not a multiple of 4 (comment)

sanskrit_parser/output_utils/__init__.py:18:11: E111 indentation is not a multiple of 4

sanskrit_parser/output_utils/__init__.py:20:7: E111 indentation is not a multiple of 4

sanskrit_parser/output_utils/__init__.py:21:3: E111 indentation is not a multiple of 4

sanskrit_parser/output_utils/__init__.py:22:3: E111 indentation is not a multiple of 4

sanskrit_parser/output_utils/__init__.py:26:3: E111 indentation is not a multiple of 4

sanskrit_parser/output_utils/__init__.py:27:3: E111 indentation is not a multiple of 4

sanskrit_parser/output_utils/__init__.py:27:25: W292 no newline at end of file

ERROR: InvocationError for command /home/travis/build/kmadathil/sanskrit_parser/.tox/lint/bin/flake8 sanskrit_parser 
```
एताः‌ समस्या अपि परिहर्तव्याः

**Comment by kmadathil** [comment]
मन्ये Python 3.9 कारणेनोत्पन्ना इयं समस्या। 3.7 उपयुज्य समीचीनैव प्रवर्तते । 
```
$ python sanskrit_parser/output_utils/__init__.py 
unable to import 'smart_open.gcs', disabling that module
/home/karthick/personal_projects/sanskrit/sanskrit_parser/sanskrit_parser/api.py:147: UserWarning: No splits found. Please check the input to ensure there are no typos.
  warnings.warn("No splits found. Please check the input to ensure there are no typos.")
/home/karthick/personal_projects/sanskrit/sanskrit_parser/sanskrit_parser/api.py:147: UserWarning: No splits found. Please check the input to ensure there are no typos.
  warnings.warn("No splits found. Please check the input to ensure there are no typos.")
श्रुति-भगवती-चरण-प्रतीका छन्दो-विचितिः-इति वेद-अङ्ग-विदः सम-आम-नन्ति । अस्य चरण-युगलस्य गतिर् एव च्छन्दःसुषमेति तत्-मर्म-विदाम् प्रेक्षा ।
```

**Comment by avinashvarna** [comment]
3.9 मध्ये files इत्यस्य उपयोगः कर्तव्य इति भाति (https://docs.python.org/3/library/importlib.html?highlight=importlib#importlib.resources.files) । 3.7-3.9 इत्येतेषु सर्वेषु समानतया एतत् कथं साधनीयम् इति अन्वेषणीयम् । (अस्माकं CI मध्ये 3.9 योजनीयम् इत्येतदपि पृथक् कार्यम् । )

lint दोषान् परिहर्तुं शक्नोमि । परन्तु एतत् कुत्र स्थापनीयम् इति विषयः चर्चनीयः । `contrib`/`examples` उत वर्तमानं स्थानम् ?

**Comment by vvasuki** [comment]
> एतत् कुत्र स्थापनीयम् इति विषयः चर्चनीयः । `contrib`/`examples` उत वर्तमानं स्थानम् ?

स्थाने निश्चीयमाने पदभेदक-यन्त्रस्याफल्गुता भाविनीति ध्यातव्या (यथा परिष्कारापवादजातम् उक्तं https://groups.google.com/g/sanskrit-programmers/c/5PUwV911Tbw इति सूत्रे)। अथ वैविध्यमपि प्रयोक्त्रपेक्षानुसारम् वर्धेत। तेनैवंविधं सुचिन्तितं स्थानम् अनुदाहरणमात्रसूचकं युक्तम्।

**Comment by avinashvarna** [comment]
Lint दोषाः मया परिहृताः । Py 3.8 testing च योजितम् ।

अस्माकं code मध्ये तु py 3.9 support योजयितुं शक्यते, परन्तु Gensim इत्यनेन py3.9 support अधुना न क्रियते । अतः सद्यः तु py 3.7/3.8 एव इति सूचनीयं स्यात् ।

**Comment by vananasun** [comment]
Bump. Having the same error on my fresh Linux installation.

**Comment by kmadathil** [comment]
केन python क्रमाङ्केन ?‌ @vananasun

**Comment by kmadathil** [comment]
@vananasun - which version of python do you see this error with?

**Comment by vananasun** [comment]
> @vananasun - which version of python do you see this error with?
3.9.x

**Comment by kmadathil** [comment]
> अस्माकं code मध्ये तु py 3.9 support योजयितुं शक्यते, परन्तु Gensim इत्यनेन py3.9 support अधुना न क्रियते । अतः सद्यः तु py 3.7/3.8 एव इति सूचनीयं स्यात् ।

@vananasun - As Avinash indicated above, we are unable to support properly 3.9.x because gensim does not. Thus, we are limited to 3.7/3.8 as of now

@avinashvarna - अस्माकं तन्त्रंशमध्ये sys.version_info दृष्ट्वा तदनुसृतं प्रवर्तनपरिवर्न्तनं निश्चेतुं शक्यं स्यात् । 3.9 सति gensim एव न प्रवर्तेत चेत् तस्यैव प्रवर्तनं निरुध्य सूचनां दातुमपि शक्यम् । अन्यत्सर्वं यथाविधि प्रवर्तेत । एवं करणीयमुत नेति चिन्त्यम् ।

**Comment by vvasuki** [comment]
>  3.9 सति gensim एव न प्रवर्तेत चेत् तस्यैव प्रवर्तनं निरुध्य सूचनां दातुमपि शक्यम् । अन्यत्सर्वं यथाविधि प्रवर्तेत । एवं करणीयमुत नेति चिन्त्यम् ।

अयम् मार्ग उत्तमो भाति।
