### ISSUE TITLE
No module named requests

### ISSUE THREAD

**Issue by codito** [kmadathil/sanskrit_parser#42]
Steps to reproduce:
```shell
> pip install sanskrit_parser
> python -m sanskrit_parser.lexical_analyzer.sandhi --split taeva 1
Traceback (most recent call last):                                                                                                                             
  File "/usr/lib64/python2.7/runpy.py", line 174, in _run_module_as_main                                                                                       
    "__main__", fname, loader, pkg_name)                                                                                                                       
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code                                                                                                  
    exec code in run_globals                                                                                                                                   
  File "/home/arun/work/hadoop-cluster/projects/geeta/.venv/lib/python2.7/site-packages/sanskrit_parser/util/inriaxmlwrapper.py", line 16, in <module>         
    import requests                                                                                                                                            
ImportError: No module named requests
```

I think `requests` needs to be explicitly declared in setup dependencies.

**Comment by codito** [comment]
Fixed in #43.
