### ISSUE TITLE
Morphological analyzer error for word without split

### ISSUE THREAD

**Issue by codito** [kmadathil/sanskrit_parser#92]
This repros on python 3.6.

```shell
> python -m sanskrit_parser.morphological_analyzer.SanskritMorphologicalAnalyzer "nara" --debug                                  master [a679a16] (!) untracked
Input String: nara                                                                                                                                             
Input String in SLP1: nara                                                                                                                                     
Start Split
End DAG generation                                                                                                                                             
End pathfinding                                                                                                                                                
Splits:
Lexical Split: [nara]                                                                                                                                          
Traceback (most recent call last):                                                                                                                             
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/arun/src/gh/sanskrit_parser/sanskrit_parser/morphological_analyzer/SanskritMorphologicalAnalyzer.py", line 359, in <module>
    main()
  File "/home/arun/src/gh/sanskrit_parser/sanskrit_parser/morphological_analyzer/SanskritMorphologicalAnalyzer.py", line 343, in main
    p = s.constrainPath(sp)
  File "/home/arun/src/gh/sanskrit_parser/sanskrit_parser/morphological_analyzer/SanskritMorphologicalAnalyzer.py", line 286, in constrainPath
    s = problem.getSolutions()
  File "/home/arun/src/gh/sanskrit_parser/.venv/lib/python3.6/site-packages/constraint/__init__.py", line 249, in getSolutions
    domains, constraints, vconstraints = self._getArgs()
  File "/home/arun/src/gh/sanskrit_parser/.venv/lib/python3.6/site-packages/constraint/__init__.py", line 294, in _getArgs
    constraints, vconstraints)
  File "/home/arun/src/gh/sanskrit_parser/.venv/lib/python3.6/site-packages/constraint/__init__.py", line 870, in preProcess
    variable = variables[0]
TypeError: 'dict_keys' object does not support indexing
```

**Comment by codito** [comment]
Appears to be related to an issue in python-constraint library: https://github.com/python-constraint/python-constraint/issues/34

**Comment by avinashvarna** [comment]
@codito, looks like you provided a fix to python-constraint. Did that resolve this issue?

**Comment by codito** [comment]
Yes, it does fix the issue.

```
> python -m sanskrit_parser.morphological_analyzer.sanskrit_morphological_analyzer "nara" --debug                                                     master [d7fb714] untracked
Input String: nara
Input String in SLP1: nara
Start Split
End DAG generation
End pathfinding
Splits:
Lexical Split: [nara]
Valid Morphologies
[(nara, ('nara', {ekavacanam, saMboDanaviBaktiH, napuMsakaliNgam}))]
[(nara, ('nara', {puMlliNgam, saMboDanaviBaktiH, ekavacanam}))]
[(nara, ('nara', {ekavacanam, saMboDanaviBaktiH, puMlliNgam}))]
Lexical Split: [na, ra]
Valid Morphologies
[(na, ('na', {napuMsakaliNgam, samAsapUrvapadanAmapadam})), (ra, ('ra', {saMboDanaviBaktiH, napuMsakaliNgam, ekavacanam}))]
[(na, ('na', {samAsapUrvapadanAmapadam, puMlliNgam})), (ra, ('ra', {saMboDanaviBaktiH, napuMsakaliNgam, ekavacanam}))]
[(na, ('na', {ekavacanam, napuMsakaliNgam, saMboDanaviBaktiH})), (ra, ('ra', {saMboDanaviBaktiH, napuMsakaliNgam, ekavacanam}))]
[(na, ('na', {avyayam})), (ra, ('ra', {saMboDanaviBaktiH, napuMsakaliNgam, ekavacanam}))]
[(na, ('na', {avyayam, nipAtam})), (ra, ('ra', {saMboDanaviBaktiH, napuMsakaliNgam, ekavacanam}))]
[(na, ('na', {ekavacanam, saMboDanaviBaktiH, puMlliNgam})), (ra, ('ra', {saMboDanaviBaktiH, ekavacanam, puMlliNgam}))]
[(na, ('na', {napuMsakaliNgam, samAsapUrvapadanAmapadam})), (ra, ('ra', {saMboDanaviBaktiH, ekavacanam, puMlliNgam}))]
[(na, ('na', {samAsapUrvapadanAmapadam, puMlliNgam})), (ra, ('ra', {saMboDanaviBaktiH, ekavacanam, puMlliNgam}))]
[(na, ('na', {avyayam})), (ra, ('ra', {saMboDanaviBaktiH, ekavacanam, puMlliNgam}))]
[(na, ('na', {avyayam, nipAtam})), (ra, ('ra', {saMboDanaviBaktiH, ekavacanam, puMlliNgam}))]
Lexical Split: [naH, a]
Valid Morphologies
[(naH, ('nf', {saMboDanaviBaktiH, ekavacanam, puMlliNgam})), (a, ('a', {saMboDanaviBaktiH, ekavacanam, puMlliNgam}))]
End Morphological Analysis
-----------
Performance
Time taken for split: 0.098212s
Time taken for path: 0.008816s
```
